- name: Create Docker Swarm
  hosts: host
  gather_facts: yes
  collections:
    - community.docker
  tasks:
    - name: Install required system packages
      apt:
        pkg:
          - cifs-utils
        state: latest
        update_cache: true

    - name: Upgrade all packages
      apt:
        name: "*"
        state: latest
        update_cache: true

    - name: Check that the reboot-requied exists
      stat:
        path: /var/run/reboot-required
      register: p

    - name: rebooting server
      ansible.builtin.reboot:
        reboot_timeout: 300
      when: p.stat.exists

    - name: determine swarm status
      shell: >
        docker info | grep 'Swarm:' | cut -d ' ' -f3
      register: swarm_status

    - name: create swarm_manager_operational group
      add_host:
        hostname: "{{ item }}"
        groups: swarm_manager_operational
      with_items: "{{ host }}"
      when: "'active' in swarm_status.stdout_lines"
      run_once: true

  hosts: host[0]
  tasks:
    - name: initialize swarm cluster
      shell: >
        docker swarm init
        --advertise-addr={{ swarm_iface | default('enp7s0') }}:2377
      when: "'swarm_manager_operational' not in groups"
      register: bootstrap_first_node
  
    - name: add initialized host to swarm_manager_operational group
      add_host:
        hostname: "{{ host[0] }}"
        groups: swarm_manager_operational
      when: bootstrap_first_node | changed
