- name: install glusterfs
  hosts: host
  tasks:
    - name: install repo
      ansible.builtin.apt_repository:
        repo: ppa:gluster/glusterfs-11
        state: present
        validate_certs: no

    - name: Update and upgrade apt packages
      apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 #One day

        
