- name: Upgrade all apt packages
  hosts: host
  gather_facts: yes
  become: false
  tasks:
    - name: Upgrade all packages
      apt:
        name: "*"
        state: latest
        update_cache: true
    - name: Check that the reboot-requied exists
      stat:
        path: /var/run/reboot-required
      register: p
    - name: rebooting server
      ansible.builtin.reboot:
        reboot_timeout: 300
      when: p.stat.exists
    - name: Create default private network
      docker_network:
        name: private
        enable_ipv6: yes
    - name: Create default public network
      docker_network:
        name: public
        enable_ipv6: yes
      
