- name: Upgrade all apt packages
  hosts: host
  gather_facts: yes
  become: false
  tasks:
    - name: Upgrade all packages
      apt:
        name: "*"
        state: latest
        update_cache: true
    - name: Check if reboot required
      stat:
        path: /var/run/reboot-required
        register: reboot_required_file

    - name: Reboot if required
      reboot:
        when: reboot_required_file.stat.exists == true
