- name: Upgrade all apt packages
  hosts: host
  gather_facts: yes
  become: false
  tasks:
    - Name: Send notification
      ansible.builtin.uri:
        url: https://ntfy.sh/basanet_lora_test
        method: POST
        body: Upgrade started
    - name: Upgrade all packages
      apt:
        name: "*"
        state: latest
        update_cache: true
    - name: Check that the reboot-requied exists
      stat:
        path: /var/run/reboot-required
      register: p
    - name: rebooting server
      ansible.builtin.reboot:
        reboot_timeout: 300
      when: p.stat.exists
    - Name: Send notification
      ansible.builtin.uri:
        url: https://ntfy.sh/basanet_lora_test
        method: POST
        body: Upgrade finished
