- name: Upgrade all apt packages
  hosts: host
  gather_facts: yes
  become: false
  tasks:
    - name: Upgrade all packages
      apt:
        name: "*"
        state: latest
        update_cache: true
    - name: Check that the reboot-requied exists
      stat:
        path: /var/run/reboot-required
      register: p
    - debug:
        msg: "Reboot required"
      when: p.stat.exists
