- name: install Traefik
  hosts: host
  gather_facts: false
  tasks:
    - name: Deploy Traefik
      community.docker.docker_container:
        name: traefik
        image: traefik:latest
        network_mode: host
        command:    
          - --log.level=DEBUG
          - --log.filePath=/logs/traefik.log
          - --accesslog=true
          - --accesslog.filepath=/logs/access.log
          - --accesslog.format=json
          #- --entrypoints.web.address=:80
          - --entrypoints.web-secure.address=:443
          - --entrypoints.mqtt.address=:1883
          - --entrypoints.mqtt-secure.address=:8883
          #- --entrypoints.dns-secure.address=:853
          #- --entrypoints.imaps.address=:993
          #- --entrypoints.imap.address=:143
          #- --entrypoints.pop3.address=:110
          #- --entrypoints.smtp.address=:25
          #- --entrypoints.pop3s.address=:995
          #- --entrypoints.smtps.address=:465
          - --providers.docker
          - --providers.docker.exposedbydefault=false
          - --providers.docker.network=public
          - --providers.file.directory=/configuration/
          - --providers.file.watch=true
          - --api
          - --api.insecure=true
          - --api.dashboard=true
          - --certificatesresolvers.le.acme.email=s.balogh@proforall.ch
          - --certificatesresolvers.le.acme.storage=/configuration/acme.json
          - --certificatesresolvers.le.acme.tlschallenge=true
          - --serverstransport.insecureskipverify=true
        ports:
          #- "995:995"
          #- "993:993"
          #- "465:465"
          - "443:443"
          #- "853:853"
          #- "8080:8080"
          #- "524:524"
          #- "8443:8443"
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock:ro"
          - traefik_configuration:/configuration
          - traefik_logs:/logs
        restart_policy: always
